### ISSUE TITLE
ABI Stable API - milestones

### ISSUE THREAD

**Issue by mhdawson** [nodejs/api#23]
## Moved to here: https://github.com/nodejs/abi-stable-node/issues/2 as it belongs in the new repo

WARNING OBSOLETE

We've been making some progress on the ABI stable API (will provide an update in WG  meeting https://github.com/nodejs/api/issues/22)

This is to capture the current view of some of the major milestones for PoC:
- [x] First example running
- [x] All NaN examples running
- [x] Module lifecycle methods
- [ ] Robust Object life-cycle handling
- [ ] Create/GetData methods for all primitive javascript types
- [ ] Exception Handling methods complete
- [ ] Error handling methods complete
- [ ] Coercion functions complete
- [ ] Buffer methods complete
- [ ] Version management methods complete
- [x] Level down running
- [ ] module 2 running
- [ ] module 3 running
- [ ] leveldown performance analysis
- [ ] module 3 performance analysis
- [ ] module 2 performance analysis
- [ ] understand impact of multi-isolate modules, e.g. `webworker-threads`
- [ ] Test suite complete
- [ ] Safety/Usability Analysis complete
- Validate API copes with other implementations:
  - [ ] Port back to 0.10.X and/or
  - [ ] Port to NodeChakra and/or
  - [ ] Port to SpiderNode
  - [ ] DukTape?
- [ ] Robust error handling
- [ ] Fill out rest of C API
- [ ] NaN/C++ wrapper feasibility analysis complete

**Comment by ianwjhalliday** [comment]
fyi @ehsan, thought you may be interested in this given your SpiderNode work.  We are beginning to port our prototype API to NodeChakra (using JSRT APIs directly instead of v8 shim) and shortly will also start porting it to an older version of Node (using older v8 API) to see how it plays out.

We're figuring it would also be good to see it ported to SpiderNode to see how SpiderMonkey APIs work out with it.  Let us know if you're interested to follow along or help out.

**Comment by boingoing** [comment]
Any plans to look into how libuv plays into the stability of the ABI?

**Comment by ehsan** [comment]
Sorry for the super late response!  I was discussing with the SpiderMonkey team (which I'm not actually a part of!) to find people who know more about SpiderMonkey to get involved in the discussion, and they're going to get in touch very soon.  I will also remain in the loop for SpiderNode specific parts.

**Comment by Qard** [comment]
In regard to the question from @boingoing, does anyone have data on usage of libuv functions in native modules, outside of AsyncWorker in nan?

**Comment by ianwjhalliday** [comment]
@ehsan no worries.  Looking forward to hearing more from the SpiderMonkey folks!

**Comment by mhdawson** [comment]
Move to here: https://github.com/nodejs/abi-stable-node/issues/2

**Comment by mhdawson** [comment]
@ehsan just let me know who you'd like to be involved in the discussions and/or invited to the weekly working meetings being held.  Also as a heads up most future discussion will likely happen in this repo: https://github.com/nodejs/abi-stable-node/

**Comment by mykmelez** [comment]
> @ehsan just let me know who you'd like to be involved in the discussions and/or invited to the weekly working meetings being held. Also as a heads up most future discussion will likely happen in this repo: https://github.com/nodejs/abi-stable-node/

Hi @mhdawson, I'm @ehsan's colleague, and I'd like to be involved in the discussions and invited to the meetings. (I'm also investigating who else at Mozilla should engage with the project. More soon.)

**Comment by mhdawson** [comment]
@mykmelez  I've put the link for the hangout for the next meeting here:

https://github.com/nodejs/abi-stable-node/issues/3

I'm away that day but the rest of the people working on the effort should be there.  I'll send a heads up that you'll be joining and you can spend some of the time getting an update as to where we are so far and then discussing what parts you might want to contribute to.

**Comment by mykmelez** [comment]
Thanks, @mhdawson! Alas, I'll be out of the office on October 14, but if the meetings are weekly, then I'll make sure to attend the next one. I've blocked off Friday, October 21 2-3pm Pacific (hoping that's the right time—please correct otherwise!).

**Comment by mhdawson** [comment]
@mykmelez its 2-3pm EST not Pacific

**Comment by mykmelez** [comment]
> @mykmelez its 2-3pm EST not Pacific

Ah, right, thanks for the correction! Ok, I've blocked off that time instead.

**Comment by ehsan** [comment]
@tbsaunde is now maintaining SpiderNode, FWIW.
